In [1]:
import pandas as pd
import numpy as np
import random
import re

In [2]:
ori_df = pd.read_excel("JHU_test.xlsx")

In [3]:
# columns
ori_df.columns

Index(['序号', '提交答卷时间', '所用时间', '来源', '来源详情', '来自IP', '1、姓名',
       '2、微信号（请务必确保准确、可添加。这是小助手联系您参加活动的方式）', '3、请填写你的学校邮箱（例：hop1@jhu.edu）',
       '4、性别', '5、(男Male)', '5、(女Female)', '5、(其他)', '6、您的年龄（周岁）？', '7、(17)',
       '7、(18)', '7、(19)', '7、(20)', '7、(21)', '7、(22)', '7、(23)', '7、(24)',
       '7、(25)', '7、(26)', '7、(27)', '7、(28)', '7、(29)', '7、(30)', '7、(31)',
       '7、(32)', '7、(32+)', '8、您所在的学校？', '9、希望TA是同校还是异校？', '10、您参加本活动的主要目的？',
       '11、您计划每日在本活动中投入多少时间？', '12、(0:00-4:00)', '12、(4:00-8:00)',
       '12、(8:00-12:00)', '12、(12:00-16:00)', '12、(16:00-20:00)',
       '12、(20:00-23:59)', '13、专业方向', '14、您希望TA与您的专业相似吗？', '15、您的性格？',
       '16、(外向)', '16、(内向)', '16、(居中)', '17、您认为自己是感性还是理性的？', '18、(感性)',
       '18、(理性)', '18、(二者相结合)', '19、您的Myers-Briggs性格类型？（选填，如果您知道）',
       '20、您希望TA的Myers-Briggs性格与自己的相同吗？', '21、猫还是狗？', '22、(音乐)', '22、(舞蹈)',
       '22、(体育)', '22、(影视)', '22、(阅读)', '22、(电竞)', '22、(旅行)', '22、(其他)',
       '23、(流行)', '23、(嘻哈)', '23、(摇滚)', '23、(古典)', '23、(电子)', '23、(爵士)',
       '23、(蓝调)', '23、(古风)', '23、(戏曲)', '23、(民族民间)', '23、(民谣)', '23、(其他)',
       '24、(爱情)', '24、(喜剧)', '24、(动作)', '24、(科幻)', '24、(古装)', '24、(历史)',
       '24、(仙侠)', '24、(武侠)', '24、(动画)', '24、(战争)', '24、(悬疑)', '24、(恐怖)',
       '24、(真人秀)', '24、(其它)', '25、您期待的恋爱相处模式？', '26、您认为最浪漫的事？',
       '27、若未为您成功匹配到CP，您是否愿意与并非是您选择的性别（比如同性）的参与者一对一地交友？'],
      dtype='object')

In [4]:
print(len(ori_df.columns))

91

In [5]:
# test data
ori_df.iloc[:1].values

array([[1, '2022/7/15 12:45:28', '83秒', '微信', nan, '68.84.9.126(国外-美国)',
        '测试员一号', 'test', 'test@gmail.com', 1, 1, 1, 0, 4, 0, 1, 1, 1, 1,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 1, 2, 1, 1, 0, 0, 0, 0, 0,
        1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 'hi', '(空)', 2]], dtype=object)

In [6]:
# 不重要 前9个
def non_imp(length,id_num):
    return ["test"+str(id_num)]*int(length)

In [7]:
# 单选 4,6,8,9,10,11,13,14,15,17,19,20,21,27
single_dict = {
    "4": 3,
    "6": 17,
    "8": 4,
    "9": 3,
    "10": 2,
    "11": 4,
    "13": 7,
    "14": 3,
    "15": 3,
    "17": 3,
    #"19": 16,
    #"20": 3,
    "21": 6,
    "27": 2,
}
def sg(q_num):
    list_val = [random.randint(1, single_dict[str(q_num)])]
    return list_val

In [8]:
# 单选中 19,20 可能是-2,-3
def sg_19(q_num):
    poss = random.randint(1,10)
    if poss < 4:
        return [-2,-3]
    else:
        return [random.randint(1,16),random.randint(1,3)]

In [9]:
# 多选：5，7，12，16，18，22，23，24
mul_dict = {
    "5": 3,
    "7": 17,
    "12": 6,
    "16": 3,
    "18": 3,
    "22": 8,
    "23": 12,
    "24": 14
}
def mul(q_num):
    list_val = []
    while (list_val == []) or (np.sum(list_val) == 0):
        list_val = [random.randint(0,1) for i in range(mul_dict[str(q_num)])]
    return list_val

In [10]:
# 填空
def fill(q_num):
    if str(q_num) == "25" or str(q_num) == "26":
        return ["empty"]

In [11]:
# 判断是单选题还是多选题
def sg_ml(q_num):
    if str(q_num) in single_dict:
        return sg(q_num)
    elif str(q_num) in mul_dict:
        return mul(q_num)
    elif str(q_num) == "25" or str(q_num) == "26":
        return ["empty"]
    elif str(q_num) == "19":
        return sg_19(q_num)
    else:
        print("error")

In [12]:
# 单选、多选题和填空列表
sg_ml_num_list = [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 22, 23, 24, 25, 26, 27]

In [13]:
# generate one 
def generate(id_num):
    generate_list = []

    #不重要9
    length = 9
    head_list = non_imp(length,id_num)
    generate_list += head_list

    #单多选22
    for i in sg_ml_num_list:
        generate_list += sg_ml(i)
    generate_list[0] = int(id_num)
    return generate_list
    # print(len(generate_list))
    # print(generate_list)

In [14]:
# gerenerate more
total_test_num = 500
final_test_list = []
for i in range(total_test_num):
    final_test_list.append(generate(i+1))

In [15]:
# test
print(len(final_test_list[0]))
print(final_test_list[0])

91
[1, 'test1', 'test1', 'test1', 'test1', 'test1', 'test1', 'test1', 'test1', 2, 0, 1, 1, 13, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 4, 1, 1, 2, 1, 0, 0, 1, 1, 0, 2, 3, 2, 1, 0, 1, 1, 1, 0, 1, 10, 3, 5, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 'empty', 'empty', 2]

In [16]:
# df_test
df_test = pd.DataFrame(final_test_list)
df_test.columns = ori_df.columns
df_test

,序号,提交答卷时间,所用时间,来源,来源详情,来自IP,1、姓名,2、微信号（请务必确保准确、可添加。这是小助手联系您参加活动的方式）,3、请填写你的学校邮箱（例：hop1@jhu.edu）,4、性别,...,24、(武侠),24、(动画),24、(战争),24、(悬疑),24、(恐怖),24、(真人秀),24、(其它),25、您期待的恋爱相处模式？,26、您认为最浪漫的事？,27、若未为您成功匹配到CP，您是否愿意与并非是您选择的性别（比如同性）的参与者一对一地交友？
0,1,test1,test1,test1,test1,test1,test1,test1,test1,2,...,1,0,0,0,0,1,0,empty,empty,2
1,2,test2,test2,test2,test2,test2,test2,test2,test2,2,...,1,0,1,1,1,0,1,empty,empty,2
2,3,test3,test3,test3,test3,test3,test3,test3,test3,3,...,1,1,0,0,1,1,1,empty,empty,1
3,4,test4,test4,test4,test4,test4,test4,test4,test4,1,...,0,1,1,1,0,1,1,empty,empty,2
4,5,test5,test5,test5,test5,test5,test5,test5,test5,1,...,1,0,1,0,0,1,1,empty,empty,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,test496,test496,test496,test496,test496,test496,test496,test496,2,...,1,1,1,1,0,0,0,empty,empty,1
496,497,test497,test497,test497,test497,test497,test497,test497,test497,3,...,0,0,0,1,1,1,1,empty,empty,2
497,498,test498,test498,test498,test498,test498,test498,test498,test498,1,...,0,0,1,1,0,1,0,empty,empty,2
498,499,test499,test499,test499,test499,test499,test499,test499,test499,2,...,0,0,1,1,1,0,0,empty,empty,2
499,500,test500,test500,test500,test500,test500,test500,test500,test500,1,...,0,1,1,0,1,1,0,empty,empty,2

In [17]:
# to excel
df_test.to_excel("random_data.xlsx")